// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {searchengine} from '../models';
import {ollama} from '../models';
import {workspace} from '../models';
import {storage} from '../models';
import {replyreview} from '../models';

export function AddSearchEngineSeed(arg1:string,arg2:string):Promise<searchengine.Seed>;

export function CancelOllamaRequest(arg1:string):Promise<void>;

export function ChatOllama(arg1:string,arg2:string,arg3:string,arg4:Array<ollama.ChatMessage>):Promise<string>;

export function CopyWorkspaceEntry(arg1:string,arg2:string,arg3:string):Promise<workspace.Snapshot>;

export function CrawlSearchEngine(arg1:searchengine.CrawlRequest):Promise<searchengine.CrawlSummary>;

export function CreateManagedWorkspaceDirectory(arg1:string):Promise<workspace.Selection>;

export function CreateWorkspaceBackup(arg1:string,arg2:string,arg3:string):Promise<workspace.BackupSummary>;

export function CreateWorkspaceDirectory(arg1:string,arg2:string):Promise<workspace.Snapshot>;

export function CreateWorkspaceFile(arg1:string,arg2:string,arg3:string):Promise<workspace.Snapshot>;

export function DeleteAllChats():Promise<void>;

export function DeleteChat(arg1:string):Promise<void>;

export function DeleteSearchEngineSeed(arg1:string):Promise<void>;

export function DeleteWorkspaceEntry(arg1:string,arg2:string):Promise<workspace.Snapshot>;

export function FetchOllamaModels(arg1:string):Promise<Array<string>>;

export function GetSearchEngineStatus():Promise<searchengine.Status>;

export function GetStorageSnapshot():Promise<storage.Snapshot>;

export function IndexSearchDocuments(arg1:Array<searchengine.IndexDocument>):Promise<searchengine.IndexSummary>;

export function InspectWorkspaceRuntime(arg1:string):Promise<workspace.RuntimeProfile>;

export function ListSearchEngineSeeds():Promise<Array<searchengine.Seed>>;

export function LoadChats():Promise<Array<Record<string, any>>>;

export function LoadReplyPreferences():Promise<Array<Record<string, any>>>;

export function OpenWorkspaceEntry(arg1:string,arg2:string):Promise<void>;

export function OpenWorkspaceInExplorer(arg1:string):Promise<void>;

export function PickWorkspaceDirectory():Promise<workspace.Selection>;

export function ReadWorkspaceFile(arg1:string,arg2:string):Promise<workspace.Document>;

export function RenameWorkspaceEntry(arg1:string,arg2:string,arg3:string):Promise<workspace.Snapshot>;

export function ReplaceReplyPreferences(arg1:Array<Record<string, any>>):Promise<void>;

export function RestoreWorkspaceBackup(arg1:string,arg2:string):Promise<workspace.Snapshot>;

export function ReviewAssistantReply(arg1:replyreview.Request):Promise<replyreview.Result>;

export function RunWorkspaceCommand(arg1:string,arg2:string,arg3:number):Promise<workspace.CommandResult>;

export function RunWorkspaceWebPreview(arg1:string,arg2:string,arg3:number):Promise<workspace.CommandResult>;

export function SaveAppSettings(arg1:storage.AppSettings):Promise<void>;

export function SaveChat(arg1:Record<string, any>):Promise<void>;

export function SaveWorkspaces(arg1:Array<Record<string, any>>):Promise<void>;

export function ScanWorkspace(arg1:string):Promise<workspace.Snapshot>;

export function SearchLocalIndex(arg1:string,arg2:number):Promise<searchengine.SearchResponse>;

export function SeedFromBrowser(arg1:storage.Snapshot):Promise<boolean>;

export function StartOllamaChatStream(arg1:string,arg2:string,arg3:string,arg4:Array<ollama.ChatMessage>):Promise<void>;

export function WriteWorkspaceFile(arg1:string,arg2:string,arg3:string):Promise<workspace.Snapshot>;

export function WriteWorkspaceFileDocument(arg1:string,arg2:string,arg3:string):Promise<workspace.Document>;
