// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSearchEngineSeed(arg1, arg2) {
  return window['go']['main']['App']['AddSearchEngineSeed'](arg1, arg2);
}

export function CancelOllamaRequest(arg1) {
  return window['go']['main']['App']['CancelOllamaRequest'](arg1);
}

export function ChatOllama(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ChatOllama'](arg1, arg2, arg3, arg4);
}

export function CopyWorkspaceEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['CopyWorkspaceEntry'](arg1, arg2, arg3);
}

export function CrawlSearchEngine(arg1) {
  return window['go']['main']['App']['CrawlSearchEngine'](arg1);
}

export function CreateManagedWorkspaceDirectory(arg1) {
  return window['go']['main']['App']['CreateManagedWorkspaceDirectory'](arg1);
}

export function CreateWorkspaceBackup(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateWorkspaceBackup'](arg1, arg2, arg3);
}

export function CreateWorkspaceDirectory(arg1, arg2) {
  return window['go']['main']['App']['CreateWorkspaceDirectory'](arg1, arg2);
}

export function CreateWorkspaceFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateWorkspaceFile'](arg1, arg2, arg3);
}

export function DeleteAllChats() {
  return window['go']['main']['App']['DeleteAllChats']();
}

export function DeleteChat(arg1) {
  return window['go']['main']['App']['DeleteChat'](arg1);
}

export function DeleteSearchEngineSeed(arg1) {
  return window['go']['main']['App']['DeleteSearchEngineSeed'](arg1);
}

export function DeleteWorkspaceEntry(arg1, arg2) {
  return window['go']['main']['App']['DeleteWorkspaceEntry'](arg1, arg2);
}

export function FetchOllamaModels(arg1) {
  return window['go']['main']['App']['FetchOllamaModels'](arg1);
}

export function GetSearchEngineStatus() {
  return window['go']['main']['App']['GetSearchEngineStatus']();
}

export function GetStorageSnapshot() {
  return window['go']['main']['App']['GetStorageSnapshot']();
}

export function IndexSearchDocuments(arg1) {
  return window['go']['main']['App']['IndexSearchDocuments'](arg1);
}

export function InspectWorkspaceRuntime(arg1) {
  return window['go']['main']['App']['InspectWorkspaceRuntime'](arg1);
}

export function ListSearchEngineSeeds() {
  return window['go']['main']['App']['ListSearchEngineSeeds']();
}

export function LoadChats() {
  return window['go']['main']['App']['LoadChats']();
}

export function LoadReplyPreferences() {
  return window['go']['main']['App']['LoadReplyPreferences']();
}

export function OpenWorkspaceEntry(arg1, arg2) {
  return window['go']['main']['App']['OpenWorkspaceEntry'](arg1, arg2);
}

export function OpenWorkspaceInExplorer(arg1) {
  return window['go']['main']['App']['OpenWorkspaceInExplorer'](arg1);
}

export function PickWorkspaceDirectory() {
  return window['go']['main']['App']['PickWorkspaceDirectory']();
}

export function ReadWorkspaceFile(arg1, arg2) {
  return window['go']['main']['App']['ReadWorkspaceFile'](arg1, arg2);
}

export function RenameWorkspaceEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameWorkspaceEntry'](arg1, arg2, arg3);
}

export function ReplaceReplyPreferences(arg1) {
  return window['go']['main']['App']['ReplaceReplyPreferences'](arg1);
}

export function RestoreWorkspaceBackup(arg1, arg2) {
  return window['go']['main']['App']['RestoreWorkspaceBackup'](arg1, arg2);
}

export function ReviewAssistantReply(arg1) {
  return window['go']['main']['App']['ReviewAssistantReply'](arg1);
}

export function RunWorkspaceCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunWorkspaceCommand'](arg1, arg2, arg3);
}

export function RunWorkspaceWebPreview(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunWorkspaceWebPreview'](arg1, arg2, arg3);
}

export function SaveAppSettings(arg1) {
  return window['go']['main']['App']['SaveAppSettings'](arg1);
}

export function SaveChat(arg1) {
  return window['go']['main']['App']['SaveChat'](arg1);
}

export function SaveWorkspaces(arg1) {
  return window['go']['main']['App']['SaveWorkspaces'](arg1);
}

export function ScanWorkspace(arg1) {
  return window['go']['main']['App']['ScanWorkspace'](arg1);
}

export function SearchLocalIndex(arg1, arg2) {
  return window['go']['main']['App']['SearchLocalIndex'](arg1, arg2);
}

export function SeedFromBrowser(arg1) {
  return window['go']['main']['App']['SeedFromBrowser'](arg1);
}

export function StartOllamaChatStream(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartOllamaChatStream'](arg1, arg2, arg3, arg4);
}

export function WriteWorkspaceFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteWorkspaceFile'](arg1, arg2, arg3);
}

export function WriteWorkspaceFileDocument(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteWorkspaceFileDocument'](arg1, arg2, arg3);
}
